[tools]
bun = "latest"
elixir = "1.18.4-otp-27"
erlang = "27.0"
gleam = "latest"
node = "22.17.0"
rebar = "3"

[tasks."migrate:new"]
description = "Create a new migration file"
run = "gleam run -m lib/migrator -- new"

[tasks."migrate:up"]
description = "Run all migrations"
run = "gleam run -m lib/migrator -- up"

[tasks."migrate:down"]
description = "Rollback all migrations"
run = "gleam run -m lib/migrator -- down"

[tasks."db:drop"]
description = "Drop the database"
run = "rm -rf development.sqlite3"

[tasks."db:create"]
description = "Create the database"
run = "touch development.sqlite3"

[tasks."config:init"]
description = "Initialise the config file"
run = "gleam run -m services/config"
